apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx
  namespace: frontend
  labels:
    app: nginx
spec:
  replicas: 3
  revisionHistoryLimit: 3  # Mantém apenas 3 revisões no histórico
  strategy:
    canary:
      stableService: nginx-stable  # 🔥 Define o serviço estável
      steps:
        - setWeight: 10  # 🔥 10% do tráfego para a nova versão
        - pause: {}      # 🔥 Pausa para monitoramento
        - setWeight: 50  # 🔥 50% do tráfego para a nova versão
        - pause: {duration: 10m}  # 🔥 Pausa de 10 minutos
        - setWeight: 100 # 🔥 100% do tráfego para a nova versão
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: nginx-html

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-stable
  namespace: frontend
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: frontend
data:
  index.html: |
    <html>
    <head><title>NGINX Test</title></head>
    <body>
      <h1>Você está conectado ao Pod:</h1>
      <h2>$(HOSTNAME)</h2>
    </body>
    </html>
