apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parking-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/pablords/k8s-lab.git"  # 🔥 Substituir pelo repositório correto
    targetRevision: master
    path: apps/backend/parking  # 🔥 Define qual pasta será sincronizada
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
