apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-center
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
        - name: control-center
          image: confluentinc/cp-enterprise-control-center:7.5.0
          ports:
            - containerPort: 9021
          env:
            - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
              value: kafka-0.kafka-hs.kafka.svc.cluster.local:9092,kafka-1.kafka-hs.kafka.svc.cluster.local:9092,kafka-2.kafka-hs.kafka.svc.cluster.local:9092
            - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
              value: zookeeper-0.zookeeper-hs.kafka.svc.cluster.local:2181,zookeeper-1.zookeeper-hs.kafka.svc.cluster.local:2181,zookeeper-2.zookeeper-hs.kafka.svc.cluster.local:2181
            - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
              value: http://schema-registry.kafka.svc.cluster.local:8081
            - name: CONTROL_CENTER_REPLICATION_FACTOR
              value: "1"
            - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
              value: "1"
            - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
              value: "1"
            # - name: CONTROL_CENTER_REST_LISTENERS
            #   value: http://0.0.0.0:9021/kafka/control-center
            # - name: CONTROL_CENTER_UI_PROXY_PREFIX_URL
            #   value: /kafka/control-center
---
apiVersion: v1
kind: Service
metadata:
  name: control-center
  namespace: kafka
spec:
  selector:
    app: control-center
  ports:
    - port: 9021
      targetPort: 9021


---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: control-center
  namespace: kafka
spec:
  hosts:
    - "control.lab.com.br" # Permitir tráfego externo de qualquer IP/Domínio
  gateways:
    - istio-system/ingress-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: control-center
            port:
              number: 9021
          weight: 100