

apiVersion: v1
kind: Namespace
metadata:
  name:  kafka

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  serviceName: kafka-hs
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka-container
          image: bitnami/kafka:3.1
          ports:
          - containerPort: 9092
            name: server
          command:
          - sh
          - -c
          - |
            HOSTNAME_FQDN="${HOSTNAME}.kafka-hs.kafka.svc.cluster.local"
            exec kafka-server-start.sh /opt/bitnami/kafka/config/server.properties \
              --override broker.id=${HOSTNAME##*-} \
              --override listeners=PLAINTEXT://:9092 \
              --override advertised.listeners=PLAINTEXT://${HOSTNAME_FQDN}:9092 \
              --override zookeeper.connect=zookeeper-hs:2181 \
              --override num.network.threads=3 \
              --override num.io.threads=8 \
              --override log.retention.hours=168 \
              --override log.segment.bytes=1073741824 \
              --override log.retention.check.interval.ms=300000
          volumeMounts:
            - name: kafka-pvc
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: kafka-pvc
      spec:
        storageClassName: standard
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-hs
  namespace: kafka
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: server
  clusterIP: None
  selector:
    app: kafka

---


kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: zookeeper
  namespace: kafka
  labels:
    app: zookeeper
spec:
  serviceName: zookeeper-hs
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
        - name: fix-perms
          image: busybox
          command: ["sh", "-c", "chown -R 1001:1001 /bitnami/zookeeper"]
          volumeMounts:
            - name: zookeeper-pvc
              mountPath: /bitnami/zookeeper
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.7.1
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          volumeMounts:
            - name: zookeeper-pvc
              mountPath: /bitnami/zookeeper
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-pvc
      spec:
        storageClassName: standard
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-hs
  namespace: kafka
  labels:
    app: zookeeper
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
  selector:
    app: zookeeper



