

apiVersion: v1
kind: Namespace
metadata:
  name:  kafka

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  serviceName: kafka-hs
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka-container
          image: bitnamilegacy/kafka:3.4.0
          ports:
          - containerPort: 9092
            name: server
          command:
          - sh
          - -c
          - |
            # Memória reservada para a JVM (ajuste para 50-60% do "limits.memory" do seu Pod)
            export KAFKA_HEAP_OPTS="-Xms1G -Xmx1G"
            
            # Otimizações do Garbage Collector para garantir baixíssima latência
            export KAFKA_JVM_PERFORMANCE_OPTS="-XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35"
            
            # Monta o endereço de rede completo (FQDN) do pod baseado no DNS do Kubernetes
            HOSTNAME_FQDN="${HOSTNAME}.kafka-hs.kafka.svc.cluster.local"
            # somente para dev auto.create.topics.enable=true
            
            # Comando de inicialização do Broker Kafka
            exec kafka-server-start.sh /opt/bitnami/kafka/config/server.properties \
              --override broker.id=${HOSTNAME##*-} \
              --override listeners=PLAINTEXT://:9092 \
              --override advertised.listeners=PLAINTEXT://${HOSTNAME_FQDN}:9092 \
              --override zookeeper.connect=zookeeper-hs:2181 \
              --override num.network.threads=6 \
              --override num.io.threads=16 \
              --override log.retention.hours=168 \
              --override log.segment.bytes=1073741824 \
              --override log.retention.check.interval.ms=300000 \
              --override num.partitions=30 \
              --override default.replication.factor=3 \
              --override offsets.topic.replication.factor=3 \
              --override transaction.state.log.replication.factor=3 \
              --override auto.create.topics.enable=true \
              --override min.insync.replicas=2 \
              --override unclean.leader.election.enable=false
          volumeMounts:
            - name: kafka-pvc
              mountPath: /bitnami/kafka
          resources:
            requests:
              cpu: 600m
              memory: 1024Mi
            limits:
              memory: 2048Mi
  volumeClaimTemplates:
    - metadata:
        name: kafka-pvc
      spec:
        storageClassName: standard
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-hs
  namespace: kafka
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: server
  clusterIP: None
  selector:
    app: kafka

---


kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: zookeeper
  namespace: kafka
  labels:
    app: zookeeper
spec:
  serviceName: zookeeper-hs
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
        - name: fix-perms
          image: busybox
          command: ["sh", "-c", "chown -R 1001:1001 /bitnami/zookeeper"]
          volumeMounts:
            - name: zookeeper-pvc
              mountPath: /bitnami/zookeeper
      containers:
        - name: zookeeper
          image: bitnamilegacy/zookeeper:latest
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: peer
            - containerPort: 3888
              name: leader-election
          command:
            - sh
            - -c
            - |
              # so para teste em dev 
              rm -rf /bitnami/zookeeper/data/*
              # --- Ajuste de Memória do ZooKeeper ---
              # O ZooKeeper não precisa de muita memória. 1GB ou 2GB de Heap é mais que suficiente para um cluster médio/grande.
              export JVMFLAGS="-Xms1G -Xmx1G -XX:+UseG1GC"
              
              # --- Configuração de Identidade (ID) ---
              POD_INDEX="${HOSTNAME##*-}"
              export ZOO_SERVER_ID=$((POD_INDEX + 1))
              
              # --- Descoberta do Quórum ---
              export ZOO_SERVERS="zookeeper-0.zookeeper-hs.kafka.svc.cluster.local:2888:3888 zookeeper-1.zookeeper-hs.kafka.svc.cluster.local:2888:3888 zookeeper-2.zookeeper-hs.kafka.svc.cluster.local:2888:3888"
              
              # --- Inicialização ---
              exec /entrypoint.sh /run.sh
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
            - name: ZOO_LISTEN_ALLIPS_ENABLED
              value: "yes"
          volumeMounts:
            - name: zookeeper-pvc
              mountPath: /bitnami/zookeeper
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-pvc
      spec:
        storageClassName: standard
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-hs
  namespace: kafka
  labels:
    app: zookeeper
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: peer
      port: 2888
      protocol: TCP
    - name: leader-election
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper



