apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
  namespace: backend
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS parking;
    DROP USER IF EXISTS 'parking'@'%';
    CREATE USER 'parking'@'%' IDENTIFIED BY 'parking';
    GRANT ALL PRIVILEGES ON parking.* TO 'parking'@'%';
    FLUSH PRIVILEGES;

    USE parking;
    
    CREATE TABLE IF NOT EXISTS slots (
        id INT AUTO_INCREMENT PRIMARY KEY,
        occupied BOOLEAN NOT NULL
    );
    
    INSERT INTO slots (occupied) VALUES (false);
    INSERT INTO slots (occupied) VALUES (false);
    INSERT INTO slots (occupied) VALUES (false);
    INSERT INTO slots (occupied) VALUES (false);
    INSERT INTO slots (occupied) VALUES (false);