apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: backend
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
    tier: mysql
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: backend
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          resources:
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_USER
              value: parking
            - name: MYSQL_PASSWORD
              value: parking
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d/ 
      volumes:
      - name: init-db
        configMap:
          name: mysql-init-scripts # Nome do ConfigMap
          

