apiVersion: v1
kind: Service
metadata:
  name: argo-rollouts
  namespace: argo-rollouts
spec:
  selector:
    app.kubernetes.io/name: argo-rollouts
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP


---

apiVersion: v1
kind: Service
metadata:
  name: argo-rollouts-dashboard
  namespace: argo-rollouts
spec:
  selector:
    app.kubernetes.io/component: rollouts-dashboard
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3100
      targetPort: 3100