apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ranking-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/pablords/k8s-lab.git"
    targetRevision: marketplace
    path: apps/marketplace/ml/ranking-service
  destination:
    server: https://kubernetes.default.svc
    namespace: marketplace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
