apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-ranking-service
  namespace: marketplace
  labels:
    app: ml-ranking-service
spec:
  selector:
    matchLabels:
      app: ml-ranking-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8084"
        prometheus.io/path: "/metrics"
      labels:
        app: ml-ranking-service
    spec:
      nodeName: minikube
      containers:
      - name: ml-ranking-service
        image: 192.168.49.5:5000/pablords/ml-ranking-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: REDIS_HOST
          value: "redis.marketplace.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: OPENSEARCH_HOST
          value: "opensearch.observability.svc.cluster.local"
        - name: OPENSEARCH_PORT
          value: "9200"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.observability.svc.cluster.local:4317"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        - name: OTEL_LOGS_EXPORTER
          value: "none"
        livenessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ml-ranking-service
  namespace: marketplace
spec:
  selector:
    app: ml-ranking-service
  ports:
  - port: 8084
    targetPort: 8084
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ml-ranking-service-hpa
  namespace: marketplace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ml-ranking-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
