apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-query.observability.svc.cluster.local:16686
    isDefault: false
    version: 1
    editable: true
