apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-exporter
  namespace: observability
  labels:
    app: opensearch-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-exporter
  template:
    metadata:
      labels:
        app: opensearch-exporter
    spec:
      containers:
      - name: opensearch-exporter
        image: prometheuscommunity/elasticsearch-exporter:v1.6.0
        args:
        - --es.uri=http://opensearch.observability.svc.cluster.local:9200
        - --es.all
        ports:
        - containerPort: 9114
          name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-exporter
  namespace: observability
spec:
  selector:
    app: opensearch-exporter
  ports:
  - port: 9114
    targetPort: 9114
    name: metrics
