apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: observability
spec:
  serviceName: opensearch
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      initContainers:
        - name: fix-perms
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/opensearch/data"]
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.11.0
        env:
        - name: discovery.type
          value: single-node
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: DISABLE_SECURITY_PLUGIN
          value: "true"
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
  volumeClaimTemplates:
  - metadata:
      name: opensearch-data
    spec:
      storageClassName: standard
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: observability
spec:
  selector:
    app: opensearch
  ports:
  - port: 9200
    targetPort: 9200

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: opensearch-vs
  namespace: observability
spec:
  hosts:
    - "opensearch.lab.com.br"
  gateways:
    - istio-system/ingress-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: opensearch.observability.svc.cluster.local
            port:
              number: 9200
